name: Deploy FastAPI App

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: cvoapi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set GOOGLE_API_KEY environment variable
        run: echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> $GITHUB_ENV

      - name: Deploy to Google Cloud Run (using Buildpacks)
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: fastapi-image-personality
          region: us-central1
          source: .
          env_vars: GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
